
# 

length = {'m': 1,
          'cm': 1/100,
          'mm': 1/1000,
          'in': 2.54/100,
          'mil': 2.54/100/1000,
          'ozCu': 34.8e-6,
          'km': 1000,
          'mi': 1609.344,
          'nmi': 1852,
          'yd': 0.9144,
          'ft': 0.3048}

area = {'m2': 1,
        'cm2': (1/100)**2,
        'mm2': (1/1000)**2,
        'in2': (2.54/100)**2,
        'mil2': (2.54/100/1000)**2,
        'km2': 1000**2,
        'ha': 1e4,
        'a': 100,
        'mi2': 1609.344**2,
        'yd2': 0.9144**2,
        'ft2': 0.3048**2}

volume = {'m3': 1,
          'cm3': (1/100)**2,
          'mm3': (1/1000)**2,
          'in3': (2.54/100)**2,
          'mil3': (2.54/100/1000)**2,
          'yd3': 0.9144**2,
          'ft3': 0.3048**2,
          'l':(1/10)**3,
          'ml':(1/10)**3 * 1e-3,
          'galUS': 0.00378541,
          'galUK': 0.00454609}

time = {'s': 1,
        'min': 60,
        'h': 60*60,
        'd': 60*60*24}

speed = {'m/s': 1,
         'km/h': 1/3600,
         'kn': 1852/3600,
         'mph': 0.44704,
         'c': 299792458}

acceleration = {'m/s2': 1,
                'g': 9.80665}

# mass
# power
# energy
# pressure
# force
# density

# temperature = {'K': [1, 0],
#                'F': [1, 1]}

CMAT = {'LENG': length,
        'AREA': area,
        'VOL': volume,
        'TIME': time,
        'SPEED': speed,
        'ACC': acceleration}

#%% ---------------------------------------------------------------------------
# Functions

def new_matrix_and_edit(f, nrows, ncols):
    f.write(f'{ncols}\n')
    f.write(f'{nrows}\n')
    f.write('NEWMAT\n')
    f.write('EDIT\n')
     
def insert_alpha(f, alpha):
    f.write(f'"{alpha}"\n')
    f.write('ASTO ST X\n')
    f.write('→\n')
    
def insert_number(f, number):
    f.write(f'"{number}"\n')
    f.write('→\n')

#%% ---------------------------------------------------------------------------
# Start autogeneration of file
   
f = open('CRMATS.hp42s', 'w')
f.write('# AUTOGENERATED FILE\n')

#%% ---------------------------------------------------------------------------
# Generate categories matrix

f.write('LBL "CRMATS"\n')
new_matrix_and_edit(f, 1, len(CMAT))
for i in range(len(list(CMAT))):
    insert_alpha(f, list(CMAT)[i])
f.write('EXITALL\n')
f.write('STO "CCAT"\n')

#%% ---------------------------------------------------------------------------
# Generate conversion matrices

for i in range(len(list(CMAT))):
    
    cat_details = list(CMAT.values())[i]
    unit_list = list(cat_details)
    unit_arg = list(cat_details.values())
    
    f.write(f'{len(unit_list)}\n')
    if(isinstance(unit_arg[0], list)):
        f.write(f'{3}\n')
    else:
        f.write(f'{2}\n')
    f.write('NEWMAT\n')
    f.write('EDIT\n')
        
    for j in range(len(cat_details)):
        f.write(f'"{unit_list[j]}"\n')
        f.write('ASTO ST X\n')
        f.write('→\n')
        
        if(isinstance(unit_arg[j], list)):
            f.write(f'{unit_arg[j][0]}\n')
            f.write('→\n')
            f.write(f'{unit_arg[j][1]}\n')
            f.write('→\n')
        else:
            f.write(f'{unit_arg[j]}\n')
            f.write('→\n')
    
    f.write('EXITALL\n')
    f.write(f'STO "{list(CMAT)[i]}"\n')

f.write('END\n')
f.close()
